### ISSUE TITLE
Error: Network Error

### ISSUE THREAD

**Issue by fityanaula** [mzabriskie/axios#1012]
I wonder why several API cannot be accessed?
I found these API and I tried this out but didn't work. I even created my own API with WCF RESTful and hosted it on azure.

1. http://pp53.azurewebsites.net/pp53service.svc/viewprovincelist
2. https://www.getpostman.com/collections/1d8df8b0b5bf27e5009b

But these API are worked.

1. https://api.myjson.com/bins/1cfkej
2. http://jsonplaceholder.typicode.com/todos
3. https://api.github.com/users/fityanaula

Please let me know where I am wrong, is it because my API or what?

Here's what I've tried:
```
import React from 'react';
import axios from 'axios';

export class viewDetailPP53 extends React.Component {
    constructor(props) {
        super(props);
        this.state = { count : [] };        
    }

    componentDidMount(){
        var self = this;
        // try with this https://api.myjson.com/bins/1cfkej it's worked
        axios.get('http://pp53.azurewebsites.net/pp53service.svc/viewprovincelist')
        .then(function (results) {
            self.setState({ count: results.data });
        })
        .catch(function (error) {
            console.log(error);
        });
    }

    render() { 
        return(
            <div>
                <table>
                    <thead>
                        <tr>
                            <th>column 1</th>
                            <th>column 2</th>
                        </tr>          
                    </thead>
                    <tbody>
                        {this.state.count.map((a, i) => <TableRow key = {i} count = {a} />)}
                    </tbody>
                </table>
            </div>
        );
    }
}

class TableRow extends React.Component {
   render() {
      return (
         <tr>
            <td>{this.props.count.idProvince}</td>
            <td>{this.props.count.province}</td>
         </tr>
      );
   }
}
```

And the error:
```
Error: Network Error
config:Object {adapter: , transformRequest: Object, transformResponse: Object, …}
message:"Network Error"
request:XMLHttpRequest {onreadystatechange: , readyState: 4, timeout: 0, …}
response:undefined
stack:"Error: Network Error\n    at createError (http://localhost:3000/static/js/bundle.js:1546:15)\n    at XMLHttpRequest.handleError (http://localhost:3000/static/js/bundle.js:1075:14)"
__proto__:Object {name: "Error", message: "", constructor: , …}
```

**Comment by fionsay** [comment]
Hi, I got the problem too . Can u tell me how did u fixed it?

**Comment by blinkcat** [comment]
same problem , can you share your solution?

**Comment by fityanaula** [comment]
Sorry for late reply. I got problem with CORS configuration in my API 😂 so, be sure to check your CORS so that you can access your axios with no problem. Some url like this http://jsonplaceholder.typicode.com/todos works. Because they have no problem with CORS lol.
