### ISSUE TITLE
Function.axios.(anonymous function) [as post]

### ISSUE THREAD

**Issue by kumpanen** [mzabriskie/axios#170]
Hi.
Im using this in a expressjs, node.js project. I try to make a axios.post call and it works in localhost. When i instead use it in a ubuntu server it gives me the error below. Im not sure how to handle this error. Any tips or ideas?
<pre>
    at Function.axios.(anonymous function) [as post] (/opt/testapp/node_modules/axios/lib/axios.js:77:16)
    at sendRequest (/opt/testapp/controllers/main.js:252:9)
    at Object.<anonymous> (/opt/testapp/controllers/main.js:264:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
</pre>

The call is a .post call:
<pre>axios.post(url, data, config).then( ...</pre>

**Comment by mzabriskie** [comment]
What version of axios are you using?

**Comment by kumpanen** [comment]
Axios v0.7.0. Node is v0.10.32. Kind of old node. Should i try to update both?

**Comment by mzabriskie** [comment]
Definitely worth a try.

**Comment by kumpanen** [comment]
@mzabriskie Updating node solved the issues. Thanks for your help!
