### ISSUE TITLE
Warnings with Bluebird

### ISSUE THREAD

**Issue by levrik** [mzabriskie/axios#380]
If I use Bluebird as Promise implementation I get the following warning on every rejected request:

```
Warning: a promise was rejected with a non-error: [object Object]
    at settle (eval at <anonymous> (http://localhost:8080/app.js:2925:2), <anonymous>:16:5)
From previous event:
    at dispatchRequest (eval at <anonymous> (http://localhost:8080/app.js:2883:2), <anonymous>:11:10)
```

**Comment by mzabriskie** [comment]
What version of axios are you using?

**Comment by levrik** [comment]
@mzabriskie 0.12.0

**Comment by levrik** [comment]
Okay, I see. This is fixed by #345.
Thanks!

**Comment by zmts** [comment]
@levrik How you integrate Bluebird to Axios ? Need help plz!

**Comment by levrik** [comment]
@zmts Just looked into my code and found this:
```javascript
import Promise from 'bluebird';

// overwrite native Promise implementation with Bluebird's (for axios)
window.Promise = Promise;
```
