### ISSUE TITLE
v0.14.0 incompatible with nock v8.0.0

### ISSUE THREAD

**Issue by geraldfullam** [mzabriskie/axios#458]
I recently updated from axios v0.12.0 to v0.14.0 and my unit tests containing nock js began failing. Rolling axios back to latest previous version v0.13.1 fixed the incompatibility issue.

The error I was getting from axios in my unit tests containing nock calls looked like this:

```
TypeError: Cannot read property 'slice' of null
  at dispatchHttpRequest (node_modules/axios/lib/adapters/http.js:84:37)
  at new Promise (node_modules/core-js/modules/es6.promise.js:191:7)
  at httpAdapter (node_modules/axios/lib/adapters/http.js:19:10)
  at run (node_modules/core-js/modules/es6.promise.js:87:22)
  at node_modules/core-js/modules/es6.promise.js:100:28
  at flush (node_modules/core-js/modules/_microtask.js:18:9)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by yanivefraim** [comment]
Not sure this is related to nock (I use nock and it is working). Can you add code example?

**Comment by yanivefraim** [comment]
I have an [example](https://github.com/wix/react-fullstack-seed/blob/master/src/containers/SiteList/SiteList.spec.js#L29) with nock @ axiosV0.15.2 - everything is working fine. I think that this issue is not related to nock / was already fixed. We might consider closing it..

**Comment by geraldfullam** [comment]
I think you're right. Please, feel free to close this issue. Thanks for the response.
