### ISSUE TITLE
Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by ryanaleksander** [mzabriskie/axios#506]
Got this error while doing some react server side rendering

Stack trace

```
 TypeError: Cannot read property 'slice' of null
    at dispatchHttpRequest (E:\Projects\real-estate\node_modules\axios\lib\adapters\http.js:84:37)
    at httpAdapter (E:\Projects\real-estate\node_modules\axios\lib\adapters\http.js:19:10)
    at dispatchRequest (E:\Projects\real-estate\node_modules\axios\lib\core\dispatchRequest.js:52:10)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Action

```
import axios from 'axios';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_POSTS = 'FETCH_POSTS';
const GET_POSTS_URI = '/api/posts';

export const fetchPosts = () => {
        let posts = axios.get(GET_POSTS_URI).catch(err => console.log(err));
        return {
            type: FETCH_POSTS,
            payload: posts
        }
}
```

API

```
app.get('/api/posts', function(req, res, next) {
    Post.model.find()
        .exec()
        .then(function(posts) {
            res.send(posts);
        }, function(err) {
            return next(err);
        });
})
```

I still got the JSON response in the network tab in dev tool, but I could not retrieve the JSON response in the reducers

**Comment by tinpee** [comment]
I got the same error and i realized that:
- In client-side, when get a short-URI like `/api/posts`, axios known what host is base on base url in browser.
- But in server side rendering, it doesn't known.
So, you must provide full-URI for axios.
Hope this help !

**Comment by nickuraltsev** [comment]
Yes, I think @tinpee is right. Thank you!

**Comment by slavab89** [comment]
@nickuraltsev I'm facing the same issue.
My config however is the following
```javascript
const api = axios.create({ timeout: 5000 });
api.defaults.baseURL = config.outAPI; // This is some endpoint that i get from the config
api.get('/api/something');
```

However, if i use the following code then i'm not getting this issue.
```javascript
const api = axios.create({ timeout: 5000, baseURL: config.outAPI });
api.get('/api/something');
```

I do think it something worth looking into... even though there is a workaround which is using the full url
