### ISSUE TITLE
set maxRedirects=0 in nodejs error

### ISSUE THREAD

**Issue by rindybo** [mzabriskie/axios#523]
```
request.create().head('http://www.baidu.com/link?url=HKEi4FJLzbKncPmQvo0rFgZyJMXefuV3p87_SE9zBqCwzeV5L3R4xvkTgWFJtDYn', {
        maxRedirects: 0,
        validateStatus: function (status) {
            return status >= 200 && status < 303;
        }

    })
    .then(respone => {
        console.log(JSON.stringify(respone.headers))
    }).catch(err => {
        // console.dir(err)
    })
```
"validateStatus" this function not work

Error: Request failed with status code 302
    at createError (D:\Project\EasyCrawler\node_modules\axios\lib\core\createError.js:15:15)
    at settle (D:\Project\EasyCrawler\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (D:\Project\EasyCrawler\node_modules\axios\lib\adapters\http.js:168:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by mzabriskie** [comment]
If you `console.log` in `validateStatus` is it ever called?
