### ISSUE TITLE
Problem with Universal Rendering

### ISSUE THREAD

**Issue by Gregcop1** [mzabriskie/axios#556]
Hi. I encounter an issue with window in universal rendering.

```
FAILED: window is not defined ReferenceError: window is not defined
at Object.<anonymous> (xxxxx/node_modules/js-data-http/dist/webpack:/~/axios/lib/adapters/xhr.js:16:1)
at __webpack_require__ (xxxxx/node_modules/js-data-http/dist/js-data-http.js:38:30)
at executor (xxxxx/node_modules/js-data-http/dist/webpack:/~/axios/lib/core/dispatchRequest.js:31:1)
at dispatchRequest (xxxxx/node_modules/js-data-http/dist/webpack:/~/axios/lib/core/dispatchRequest.js:19:1)
at process._tickCallback (internal/process/next_tick.js:103:7)
(node:25772) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): ReferenceError: window is not defined
```

I don't know but maybe it will help to that regarding [this function](https://github.com/mzabriskie/axios/blob/d963368960e2e1b3ec6a2eb78ff8fd085e4e229c/lib/defaults.js#L17), different modules should be required for browser or node, but in [the dist file](https://github.com/mzabriskie/axios/blob/master/dist/axios.js#L550), it's not. The module required contains call to window but it's not defined on server side.

**Comment by nickuraltsev** [comment]
The UMD build is only for browsers. Please use the npm package in Node.js.

**Comment by Gregcop1** [comment]
I'm not import it directly, I'm using js-data, but I go check with them. Tanks a lot
