### ISSUE TITLE
Hi Matt - trying to use your library on Lambda and getting "TypeError: relativeURL.replace is not a function"

### ISSUE THREAD

**Issue by roboweaver** [mzabriskie/axios#611]
Running a Lambda function that calls axios to hit a Workfront API and getting an error:

`2016-12-22T15:59:05.264Z	ced2f412-ccbd-4d5c-b87b-2127fcc0a773	TypeError: relativeURL.replace is not a function
at combineURLs (/var/task/node_modules/axios/lib/helpers/combineURLs.js:11:58)
at Axios.request (/var/task/node_modules/axios/lib/core/Axios.js:41:18)
at Axios.(anonymous function) [as get] (/var/task/node_modules/axios/lib/core/Axios.js:67:17)
at Function.wrap [as get] (/var/task/node_modules/axios/lib/helpers/bind.js:9:15)
at /var/task/users/triggerCreate.js:58:17
at Array.forEach (native)
at module.exports.triggerCreate.event.Records.forEach (/var/task/users/triggerCreate.js:47:16)`

The call is just axios.get:

`			return axios.get({
				url: '/attask/api-asp/login',
				params: data,
				headers: {
					"cache-control": "no-cache",
					"content-type": "application/json"
				}
			})`

**Comment by rubennorte** [comment]
That's normal. You can only use relative urls '/attask/...' in the browser. In other environments you must provide the full URL ('http://.../attask/...') or the baseUrl option.
