### ISSUE TITLE
Auth header with JWT - socket hang up

### ISSUE THREAD

**Issue by ttbarnes** [mzabriskie/axios#622]
I'm trying to test a protected GET endpoint with axios, but I can't get past our auth check. 

I can't see anything wildly different in the test env logs that differ from the logs in dev environment. I'm sending an Authorization header with JWT, the endpoint is correct. This only happens when I run with axios config. Is there something i'm missing? 

Always get this error:

```
 Error: socket hang up
    at createHangUpError (_http_client.js:253:15)
    at Socket.socketOnEnd (_http_client.js:345:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  code: 'ECONNRESET',
```

I know that this error means that the connection was closed - by a crash on server or a syntax error, but I don't understand what could be causing this (or what could be missing) from using axios.

Here is the test:

```
describe('GET /api/private', () => {
  it('should work', () => {
    const USER_JWT_VALID = 'JWT asdf.....';

    let instance = axios.create();
    instance.defaults.headers.common['Authorization'] = USER_JWT_VALID;

    return instance.get('http://localhost:3000/api/private')
      .then((response) => {
        expect(response.data).to.be.an('object');
      }).catch((error) => {
        console.log('err ', error); //socket hang up
      });
  });
});
```

The endpoint uses node passport to check the JWT, then proceeds to a function that will return other things. With this test, we do not pass the authorisation check. If unauthorised, we would get an unauth response, but i'm not getting any response at all.

Other simpler GET endpoints work perfectly - specifically an endpoint that doesn't require authorization header.

I'm still learning some node things, maybe something silly i'm doing. 

I've gone through the documentation and tried setting the auth header in different ways, but always get the same result.

**Comment by ttbarnes** [comment]
Sorry - this is nothing to do with axios. This seems to be a bug with passport-jwt (auth GET requests are not getting past passport auth) Thanks all the same! :)
