### ISSUE TITLE
ENOTFOUND error, but url works in Chrome

### ISSUE THREAD

**Issue by ir-fuel** [mzabriskie/axios#720]
this is my config

```
var axiosGet = axios.create({
  baseURL: 'http://api.apixu.com/v1',
  timeout: 1000,
  headers: {'Accept-Type': 'application/json'}
});
```

this is the call I do
```
axiosGet.get(`/forecast.json?key=${apiKey}&q=${locationString}&days=${diff}`)
```

This is what the URL looks like inside axios
```
http://api.apixu.com/v1/forecast.json?key=*CENSORED*&q=50.437,5.972&days=1
```

This is the error I get:
```
{ Error: getaddrinfo ENOTFOUND api.apixu.com api.apixu.com:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.apixu.com',
  host: 'api.apixu.com',
  port: 80,
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 1000,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Accept-Type': 'application/json',
        'User-Agent': 'axios/0.15.3' },
     baseURL: 'http://api.apixu.com/v1',
     method: 'get',
     url: 'http://api.apixu.com/v1/forecast.json?key=*CENSORED*&q=50.437,5.972&days=1',
     data: undefined },
  response: undefined }
Error: getaddrinfo ENOTFOUND api.apixu.com api.apixu.com:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

Running the same url in Chrome works fine.

What could this be?

I am running 0.15.3 on node 7, and the calls are done server-side (running on my machine at the moment)

**Comment by ir-fuel** [comment]
Just tested by replacing the host with its IP
This gives a 404 response ...

**Comment by ir-fuel** [comment]
Rebooting the computer solved it ....
