### ISSUE TITLE
Request with port in baseUrl is sent over port 80

### ISSUE THREAD

**Issue by markstickley** [mzabriskie/axios#729]
This is the error I'm getting:
```
{ Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80,
  config:
   { transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        'User-Agent': 'axios/0.13.1',
        'Content-Length': 2 },
     timeout: 5000,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     method: 'post',
     baseUrl: 'http://localhost:8882',
     url: '/iam/json/customers/authenticate',
     data: '{}' },
  response: undefined }
```

Am I doing something wrong here or is this a bug? Thanks!

**Comment by erikreyna** [comment]
What happens if you take baseUrl out of the config and just add it to url?

`url: 'http://localhost:8882/iam/json/customers/authenticate',`

**Comment by markstickley** [comment]
Thanks! I'll try it out on Monday morning. Interestingly I tried changing localhost to foo and it still resolved to 127.0.0.1 so I think something strange is going on outside of the regular config...

**Comment by markstickley** [comment]
Ack sorry. I can see what I've done. `baseUrl` is incorrect - it should be `baseURL`. Thanks for taking the time to look; closing the issue :)

**Comment by kamok** [comment]
In my issue, I had to add `https://` infront of my host.
