### ISSUE TITLE
Unable to make request successfully using Axios which otherwise works fine (using fetch / curl)

### ISSUE THREAD

**Issue by purezen** [mzabriskie/axios#745]
A call made via,
```
curl -X POST -H "X-Token: secrettext" -H "Cache-Control: no-cache" -d '{"userid":"abcde"}' "https://one.server.com/endpoint"
```
returns a valid response.

However, I am not able to make a similar request using Axios. I tried with,
```js
axios.post(`https://one.server.com/endpoint`, {
            headers: {'X-Token': 'secrettext'},
            userid: 'abcde'
          })
          .then(function(response) {
            res.json({res: response.data})
          })
          .catch(function(err) {
            console.log(err)
          })
```

The error log says,
```
{ Error: Request failed with status code 400
    at createError (/Users/purezen/goodbox/internal-portal-server/node_modules/axios/lib/core/createError.js:15:15)
    at settle (/Users/purezen/goodbox/internal-portal-server/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/purezen/goodbox/internal-portal-server/node_modules/axios/lib/adapters/http.js:186:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json;charset=utf-8',
        'User-Agent': 'axios/0.15.3',
        'Content-Length': 99 },
     method: 'post',
     url: 'https://one.server.com/endpoint',
     data: '{"headers":{"X-Token":"secrettoken"},"data":"{\\"userid\\": \\"abcde\\"})"}' },
  response:
   { status: 400,
     statusText: 'Bad Request',
     headers:
      { 'content-type': 'text/html; charset=UTF-8',
        'content-length': '1555',
        date: 'Wed, 08 Mar 2017 07:51:27 GMT' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'post',
        url: 'https://one.server.com/endpoint',
        data: '{"headers":{"X-Token":"secrettoken"},"data":"{\\"userid\\": \\"abcde\\"})"}' },
     request:
      Writable {
        _writableState: [Object],
        writable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 1,
        _onNativeResponse: [Function],
        _currentRequest: [Object],
        _currentUrl: 'https://accounts.google.com/o/oauth2/auth?state=https%253A%252F%252F%252Fquery%252Flive%&redirect_uri=http%3A%2F%..%2Fquery&hd=&response_type=code&client_id=532241711518-55vgr0psqoj9claohlmh35pk4v9u9cao.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&access_type=offline',
        _currentResponse: [Object] },
     data: '<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">\n  <title>Error 400 (Bad Request)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>400.</b> <ins>That’s an error.</ins>\n  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>\n'
```

**Comment by QuentinDejean** [comment]
HI @purezen,

Looking at your request, it looks like your header is being sent in the request body instead of the `headers`.

I think you'll need to pass the headers in a different way using `axios.post`: https://github.com/mzabriskie/axios#axioscreateconfig

Or instead:
```axios({
url: '',
method: 'post',
headers: {}
})
```

Does that make sense?

**Comment by rubennorte** [comment]
Closing due to inactivity (and the issue seems to be in the way the request is configured).

**Comment by nckraghu** [comment]
@QuentinDejean Thanks, that solved the issue for me!

**Comment by BunkaS** [comment]
I was having a similar issue in react-native: 
The following always returned 400: axios.post(url, data, header);
While the next one returned 200: axios({url: url, method: 'post', data: data, headers: header }); 
Is this an axios post bug.

**Comment by Mutmatt** [comment]
@BunkaS having your full code of the `400` would be useful as you don't list how the signature looks it should look something like this:
```javascript
axios.post(url, data, {
    headers: { 'key': 'value' }
});
```
