### ISSUE TITLE
"Error: write after end" after updating from 0.14 to 0.16.2 (latest)

### ISSUE THREAD

**Issue by olalonde** [mzabriskie/axios#964]
I'm getting the following error after upgrading from 0.14 to 0.16.2:

```
        { [Error: write after end] config: { adapter: [Function: httpAdapter], baseURL: 'http://localhost:56905', data: { _boundary: '--------------------------274310387172221772246445', _currentStream: null, _events: {}, _eventsCount: 0, _overheadLength: 162, _released: true, _streams: [], _valueLength: 4, _valuesToMeasure: [], dataSize: 0, maxDataSize: 2097152, pauseStreams:true, readable: true, writable: false }, headers: { Accept: 'application/json, text/plain, */*', 'Content-Type': 'multipart/form-data; boundary=--------------------------274310387172221772246445', 'User-Agent': 'axios/0.16.2', 'x-identity-token': 'test123' }, maxContentLength: -1, method: 'post', timeout: 0, transformRequest: { 0: [Function: transformRequest] }, transformResponse: { 0: [Function: transformResponse] }, url: 'http://localhost:56905/upload', validateStatus: [Function: validateStatus], xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN' }, request: { _bufferedWrites: [ { data: <Buffer 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 32 37 34 33 31 30 33 38 37 31 37 32 32 32 31 37 37 32 32 34 36 34 ... >, encoding: 'buffer' }, { data: <Buffer de ad be ef>, encoding: 'buffer' } ], _currentRequest: { _contentLength: null, _ended: false, _events:{ abort: [Function], aborted: [Function], error: [Function], response: [Function: bound onceWrapper], socket: [Function] }, _eventsCount: 5, _hasBody: true, _header: 'POST /upload HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: multipart/form-data; boundary=--------------------------274310387172221772246445\r\nx-identity-token: test123\r\nUser-Agent: axios/0.16.2\r\nHost: localhost:56905\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n', _headerSent: true, _last: true, _maxListeners: undefined, _onPendingData: [Function: noopPendingOutput], _redirectable: [Circular], _removedConnection: false, _removedContLen: false, _removedTE: false, _trailer: '', aborted: undefined, agent: { _events: { free: [Function] }, _eventsCount: 1, _maxListeners: undefined, defaultPort: 80, domain: null, freeSockets: {}, keepAlive: false, keepAliveMsecs: 1000, maxFreeSockets: 256, maxSockets: Infinity, options: { path: null }, protocol: 'http:', requests: {}, sockets: { 'localhost:56905:': [Object] } }, chunkedEncoding: true, connection: { _bytesDispatched: 458, _consuming: true, _events: { _socketEnd: [Function:onSocketEnd], agentRemove: [Function: onRemove], close: [Object], data: [Function: socketOnData], drain: [Function: ondrain], end: [Object], error: [Function: socketErrorListener], finish: [Function: onSocketFinish], free: [Function: onFree] }, _eventsCount: 9, _hadError: false, _handle: { _externalStream: [Object], bytesRead: 0, fd: 15, onconnection: null, onread: [Function: onread], owner: [Object], reading: true, writeQueueSize: 0 }, _host: 'localhost', _httpMessage: [Circular], _maxListeners: undefined, _parent: null, _pendingData: null, _pendingEncoding: '', _readableState: { awaitDrain: 0, buffer: [Object], decoder: null, defaultEncoding: 'utf8', destroyed: false, emittedReadable: false, encoding: null, endEmitted: false, ended: false, flowing: true, highWaterMark: 16384, length: 0, needReadable: true, objectMode: false, pipes: null, pipesCount: 0, readableListening: false, reading: true, readingMore: false, resumeScheduled: false, sync: false }, _server: null, _sockname: null, _writableState: { bufferProcessing: false, bufferedRequest: null, bufferedRequestCount: 0, corked: 0, corkedRequestsFree: [Object], decodeStrings: false, defaultEncoding: 'utf8', destroyed: false, ended: false, ending: false, errorEmitted: false, finalCalled: false, finished: false, highWaterMark: 16384, lastBufferedRequest: null, length: 0, needDrain: false, objectMode: false, onwrite: [Function: bound onwrite], pendingcb: 0, prefinished: false, sync: false, writecb: null, writelen: 0, writing: false }, allowHalfOpen: false, connecting: false, domain: null, parser: { 0: [Function: parserOnHeaders], 1: [Function: parserOnHeadersComplete], 2: [Function: parserOnBody], 3: [Function: parserOnMessageComplete], 4: null, _consumed: false, _headers: [Object], _url: '', incoming: null, maxHeaderPairs: 2000, onIncoming: [Function: parserOnIncomingClient], outgoing: [Object], socket: [Object] }, read: [Function], readable: true, server: null, writable: true }, domain: null, finished: true, maxHeadersCount: null, method: 'POST', output: [], outputCallbacks: [], outputEncodings: [], outputSize: 0, parser: { 0: [Function: parserOnHeaders], 1: [Function: parserOnHeadersComplete], 2: [Function: parserOnBody], 3: [Function: parserOnMessageComplete], 4: null, _consumed: false,_headers: [], _url: '', incoming: null, maxHeaderPairs: 2000, onIncoming: [Function: parserOnIncomingClient], outgoing: [Circular], socket: { _bytesDispatched: 458, _consuming: true, _events: [Object], _eventsCount: 9, _hadError: false, _handle: [Object], _host: 'localhost', _httpMessage: [Object], _maxListeners: undefined, _parent: null, _pendingData: null, _pendingEncoding: '', _readableState: [Object], _server: null, _sockname: null, _writableState: [Object], allowHalfOpen: false, connecting: false, domain: null, parser: [Object], read: [Function], readable: true, server: null, writable: true } },path: '/upload', res: null, sendDate: false, shouldKeepAlive: false, socket: { _bytesDispatched: 458, _consuming: true, _events: { _socketEnd: [Function: onSocketEnd], agentRemove: [Function: onRemove], close: [Object], data: [Function: socketOnData], drain: [Function: ondrain], end: [Object], error: [Function: socketErrorListener], finish: [Function: onSocketFinish], free: [Function: onFree] }, _eventsCount: 9, _hadError: false, _handle: { _externalStream: [Object], bytesRead: 0, fd: 15, onconnection: null, onread: [Function: onread], owner: [Object], reading: true, writeQueueSize: 0 }, _host: 'localhost', _httpMessage: [Circular], _maxListeners: undefined, _parent: null, _pendingData: null, _pendingEncoding: '', _readableState: { awaitDrain: 0, buffer: [Object], decoder: null, defaultEncoding: 'utf8', destroyed: false, emittedReadable: false, encoding: null, endEmitted: false, ended: false, flowing: true, highWaterMark: 16384, length: 0, needReadable: true, objectMode: false, pipes: null, pipesCount: 0, readableListening: false, reading: true, readingMore: false, resumeScheduled: false, sync: false }, _server: null, _sockname: null, _writableState: { bufferProcessing: false, bufferedRequest: null, bufferedRequestCount: 0, corked: 0, corkedRequestsFree: [Object], decodeStrings: false, defaultEncoding: 'utf8', destroyed: false, ended: false, ending: false, errorEmitted: false, finalCalled: false, finished: false, highWaterMark: 16384, lastBufferedRequest: null, length: 0, needDrain: false, objectMode: false, onwrite: [Function: bound onwrite], pendingcb: 0, prefinished: false, sync: false, writecb: null, writelen: 0, writing: false }, allowHalfOpen: false, connecting: false, domain: null, parser: { 0: [Function: parserOnHeaders], 1: [Function: parserOnHeadersComplete], 2: [Function: parserOnBody], 3: [Function: parserOnMessageComplete], 4: null, _consumed: false, _headers: [Object], _url: '', incoming: null, maxHeaderPairs: 2000, onIncoming:[Function: parserOnIncomingClient], outgoing: [Object], socket: [Object] },read: [Function], readable: true, server: null, writable: true }, socketPath: undefined, timeout: undefined, timeoutCb: null, upgradeOrConnect: false, upgrading: false, useChunkedEncodingByDefault: true, writable: true }, _currentUrl: 'http://localhost:56905', _events: { error: [Function: handleRequestError], response: [Function: handleResponse] }, _eventsCount: 2, _maxListeners: undefined, _onNativeResponse: [Function], _options: { agent: undefined, auth: undefined, headers: { Accept: 'application/json, text/plain, */*', 'Content-Type': 'multipart/form-data; boundary=--------------------------274310387172221772246445', 'User-Agent': 'axios/0.16.2', 'x-identity-token': 'test123' }, hostname: 'localhost', maxRedirects: 21, method: 'post', path: '/upload', port: '56905', protocol: 'http:' }, _redirectCount: 0, _writableState:{ bufferProcessing: false, bufferedRequest: { callback: [Function: nop], chunk: <Buffer 0d 0a 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 32 37 34 33 31 30 33 38 37 31 37 32 32 32 31 37 37 32 32 34 ... >, encoding: 'buffer', isBuf: true, next: null }, bufferedRequestCount: 0, corked: 0, corkedRequestsFree: { entry: null, finish: [Function: bound onCorkedFinish], next: null }, decodeStrings: true, defaultEncoding: 'utf8', destroyed: false, ended: false, ending: false, errorEmitted: true,finalCalled: false, finished: false, highWaterMark: 16384, lastBufferedRequest: { callback: [Function: nop], chunk: <Buffer 0d 0a 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 32 37 34 33 31 30 33 38 37 31 37 32 32 32 31 37 37 32 32 34 ... >, encoding: 'buffer', isBuf: true, next: null }, length: 58, needDrain: false, objectMode: false, onwrite: [Function: bound onwrite], pendingcb: 1, prefinished: false, sync: false, writecb: null, writelen: 0, writing: false }, domain: null, writable: true }, response: undefined }
      at: process._tickCallback (internal/process/next_tick.js:169:7)
      stack: |-
        Error: write after end
            at write_ (_http_outgoing.js:635:15)
            at ClientRequest.write (_http_outgoing.js:630:10)
            at RedirectableRequest._write (/Users/olalonde/code/binded/blockai-api/node_modules/axios/node_modules/follow-redirects/index.js:186:23)
            at doWrite (_stream_writable.js:371:12)
            at clearBuffer (_stream_writable.js:489:7)
            at onwrite (_stream_writable.js:415:7)
            at onCorkedFinish (_stream_writable.js:604:5)
            at afterWrite (_stream_writable.js:430:3)
            at onwrite (_stream_writable.js:421:7)
            at Socket._writeGeneric (net.js:770:5)
```

Here's a complete standalone test (requires Node >8) to reproduce the error:

```javascript
const test = require('blue-tape')
const axios = require('axios')
const express = require('express')
const { promisify } = require('util')
const concat = require('concat-stream')
const FormData = require('form-data')
const axiosVersion = require('axios/package.json').version

const listen = (app) => new Promise((resolve, reject) => {
  const server = app.listen((err) => {
    if (err) return reject(err)
    resolve(server)
  })
})

let closeServer
let baseURL
let port
let client
let server

const startServer = async () => {
  const app = express()

  app.post('/upload', (req, res) => {
    // console.error(req.headers)
    req.pipe(concat(() => {
      res.json({ headers: req.headers })
    }))
  })

  server = await listen(app)

  closeServer = promisify(server.close.bind(server))
  port = server.address().port
  baseURL = `http://localhost:${port}`
  client = axios.create({
    baseURL,
    /*
    headers: {
      'x-identity-token': 'test123',
    },
    */
  })
  return server
}

test('start server', startServer)

test('upload file', async (t) => {
  const buf = new Buffer('deadbeef', 'hex')
  const form = new FormData()
  form.append('some-image', buf, {
    filename: 'some-image.jpg',
    contentType: 'image/jpeg',
  })

  const headers = form.getHeaders()
  const boundaryId = headers['content-type'].substr(-24)
  t.deepEqual(headers, {
    /* eslint-disable max-len */
    'content-type': `multipart/form-data; boundary=--------------------------${boundaryId}`,
  })

  const response = await client.post('/upload', form, { headers })

  t.deepEqual(response.data, {
    headers: {
      accept: 'application/json, text/plain, */*',
      connection: 'close',
      'content-type': `multipart/form-data; boundary=--------------------------${boundaryId}`,
      host: `localhost:${port}`,
      'transfer-encoding': 'chunked',
      'user-agent': `axios/${axiosVersion}`,
    },
  })
})

test('stop server', async () => {
  await closeServer()
})
```

The test succeed with axios 0.14 but fails with 0.15.3 and 0.16.2.

**Comment by olalonde** [comment]
Edit: the test passes in ``axios@0.15.2` so the breaking change seems to be introduced in `axios@0.15.3`.

**Comment by olalonde** [comment]
https://github.com/mzabriskie/axios/compare/v0.15.2...v0.15.3

**Comment by olalonde** [comment]
I think I isolated the issue to the bump from `follow-redirect@0.0.7` to `follow-redirects@1.0.0`: https://github.com/mzabriskie/axios/compare/v0.15.2...v0.15.3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L75 ... which of course is my module, full circle!

**Comment by olalonde** [comment]
Further isolated... bug was first introduced in `follow-redirects@0.3.0` https://github.com/olalonde/follow-redirects/compare/v0.2.0...v0.3.0

**Comment by olalonde** [comment]
Updating to follow-redirects to `1.2.4` [should fix](https://github.com/olalonde/follow-redirects/issues/50) this issue.

**Comment by rubennorte** [comment]
That version is compatible with the one in the package.json, so it should work fine if you update it.

**Comment by rwpino** [comment]
https://stackoverflow.com/questions/53526860/sending-file-from-server-to-server-using-axios
