### ISSUE TITLE
Cancelling group by using "axios.default.cancelToken = ..." causes "config.cancelToken.throwIfRequested"

### ISSUE THREAD

**Issue by hesher** [mzabriskie/axios#978]
#### Summary

I running axios requests in tests and when the test logic is complete I want to cancel all active requests (which are not related to the logic of the test).
This is my init code:
```javascript
let CancelToken = axios.CancelToken;
let axiosSource = CancelToken.source();
export const axiosCancel = axiosSource.cancel;
axios.defaults.cancelToken = axiosSource.token;
```

and then, (using mocha) I run cancel like this:
```javascript
afterEach(() => {
  axiosCancel();
});
```

When `axiosCancel()` is run I get this error in the stack:
```log
Error: TypeError: config.cancelToken.throwIfRequested is not a function
    at Error (native)
    at /Users/Ben_Katz/Git/wix/user-manager/src/client/actions/fetchUserByDomain.ts:34:13 } with Error: TypeError: config.cancelToken.throwIfRequested is not a function
    at Error (native)
    at /Users/Ben_Katz/Git/wix/user-manager/src/client/actions/fetchUserByDomain.ts:34:13 +0ms
```

I don't know if this is not working because it's not supposed to work that way but the error gives me no information and as far as I can tell it's a bug.
#### Context

- axios version: v0.16.3*
- Environment:  node v6.10.4, MacOs sierra*

**Comment by jolin1337** [comment]
Maybe a stupid question but: v0.16.3, does that exist? The latest release is v0.16.2, right? 

Anyway, I am having the exact same error. I am not invoking the `axios.default.cancelToken` but I am sending the token down when the request is being executed like so:

```
axios.get('/path/to/request', {
  params: newParams,
  cancelToken: cancelToken
}).then(function (response) {
  console.log(response);
}).catch(function (error) {
  console.error(error); // <--- Here I am logging the error as @hesher mentions
});
```

After some debugging the config object in the dispatchRequest.js does not contain the function `throwIfRequested` although the function is there when I send the cancelToken into the request as parameter, everything else seems normal to me. I am mainly guessing now but maybe this issue has something to do with the fact that the function is a prototype and the call to utils.merge function removes the prototypes here: https://github.com/mzabriskie/axios/blob/3579da4cb0ebc8d29907f256cfd05e12d9c3216a/lib/core/Axios.js#L37 ?

**Comment by Bnaya** [comment]
A fast workaround for this issue:
```ts
...
const CancelToken = Axios.CancelToken;
this.source = CancelToken.source();
// OMG! AXIOS has ISSUES! it merges the cancel token incorrectly, so we trick it and move it from the prototype to the object itself
this.source.token.throwIfRequested = this.source.token.throwIfRequested;
this.source.token.promise.then = this.source.token.promise.then.bind(this.source.token.promise);
this.source.token.promise.catch = this.source.token.promise.catch.bind(this.source.token.promise);
...
```

**Comment by ru-web-designer** [comment]
I am a little curious about what does
``` javaxript
this.source.token.throwIfRequested = this.source.token.throwIfRequested;
```
do?

**Comment by Bnaya** [comment]
@ru-web-designer it copies the property from the prototype to the `this`, so the extend function will also copy it because probably the extends using hasOwnProperty or so

**Comment by ru-web-designer** [comment]
@Bnaya got it, thanks :)
