### ISSUE TITLE
In the Node.js thrown an error: read ECONNRESET

### ISSUE THREAD

**Issue by vimplus** [mzabriskie/axios#996]
#### Summary

Hello, when I was in the Node. Js to other server sends a request catch an error, has received the request and deal with the other server, but axios thrown response: undefined.

This my code:

```
async function onPaymentToBS(data) {
    const url = config.serverHost.bsWeb + '/BS/rest/payfor/doPayment';
    try {
        // 组装请求头
        var headers = generateHeaders(data);
        var params = {
            bankNo: data.bankCode,
            cityNo: data.cityCode,
            accntNo: data.accountCardID,
            accntNM: data.accountName,
            amt: data.paymentAmount
        };
        var hash = md5(data);
        headers.sign = hash;

        var response = await axios({ method: 'post', url: url, headers: headers, data: params});

        var result = response && response.data;
        return result;
    } catch (err) {
        logger.info('----- API:', url, '- The Error:', err);
        return null;
    }
}
```

Use ` try catch ` catch the error is as follows:

```
[2017-07-11 16:20:49.881] [INFO] server - ------ API: http://172.xx.x.xx:8080/api/rest/payfor/doPayment - The Error: { Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread [as _originalOnread] (net.js:572:26)
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 30000,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'Content-Length': 103,
        'Serial-No': 'I000047/11/201770756',
        AppID: 'I00004',
        Timestamp: '1499761249',
        Signature: '893521A07D25564EBD9CA6155B4DC715',
        sign: 'a509036c30a7f24f89624ca87cf5291d',
        'Content-Type': 'application/json',
        'User-Agent': 'axios/0.16.1' },
     method: 'POST',
     data: '{"bankNo":"000006","cityNo":"0100","accntNo":"62268888888888","accntNM":"Mr.Zhang","amt":"125800.00"}',
     url: 'http://172.xx.x.xx:8080/api/rest/payfor/doPayment' },
  response: undefined }
```

This error is occasional.

#### Context

- axios version: *v0.16.1*
- Environment: *node v7.4.0, GNU/Linux*

**Comment by LoganBarnett** [comment]
The connection was reset, so there is no response. You'll want to look at the error's `code` property for `ECONNRESET` and handle that case appropriately.
